package frc.robot.subsystems;


import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import frc.robot.constants.Constants.DebugConstants;
import frc.robot.constants.Constants.AutoConstants;
import frc.robot.constants.Constants.LimelightConstants;
import frc.robot.constants.TunerConstants;
import frc.robot.constants.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.VisionSubsystem.PoseObservation;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private static final double kSingleTagMaxTranslationResidualMeters = 1.0;
    private static final double kMultiTagMaxTranslationResidualMeters = 1.0;
    private static final double kSingleTagMaxHeadingResidualRadians = Math.toRadians(20.0);
    private static final double kMultiTagMaxHeadingResidualRadians = Math.toRadians(30.0);
    private final SwerveRequest.Idle m_safeIdleRequest = new SwerveRequest.Idle();
    private boolean m_pathPlannerConfigured;
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    private final VisionSubsystem vision = new VisionSubsystem(
        LimelightConstants.DRIVE_LIMELIGHT_NAME,
        LimelightConstants.PIPELINE_APRILTAG);

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        this.configurePathPlanner();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        this.configurePathPlanner();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        this.configurePathPlanner();
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(
            DebugConstants.ALLOW_SWERVE_OUTPUT && areAllModulesConnected()
                ? request.get()
                : m_safeIdleRequest
        ));
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        SmartDashboard.putData("Field", m_field);
        m_field.setRobotPose(this.getState().Pose);

        vision.getEstimatedPose()
            .filter(this::isVisionMeasurementAcceptable)
            .ifPresent(observation -> {
            this.addVisionMeasurement(
                    observation.pose(),
                    observation.timestampSeconds(),
                    LimelightConstants.VISION_STD_DEVS
            );
        });
    }

    /** Immediately replaces any latched drive request with neutral output. */
    public void requestIdle() {
        this.setControl(m_safeIdleRequest);
    }

    /** Holds every swerve output idle until the returned command is interrupted. */
    public Command safeIdleCommand() {
        return run(this::requestIdle).finallyDo(interrupted -> requestIdle());
    }

    public boolean isPathPlannerConfigured() {
        return m_pathPlannerConfigured && AutoBuilder.isConfigured();
    }

    private boolean isVisionMeasurementAcceptable(PoseObservation observation) {
        Optional<Pose2d> sampledOdometry = samplePoseAt(observation.timestampSeconds());
        if (sampledOdometry.isEmpty()) {
            return false;
        }

        Pose2d reference = sampledOdometry.get();
        double translationResidual = reference.getTranslation()
            .getDistance(observation.pose().getTranslation());
        double headingResidual = Math.abs(
            reference.getRotation().minus(observation.pose().getRotation()).getRadians());

        boolean multiTag = observation.tagCount() >= 2;
        return translationResidual <= (multiTag
                ? kMultiTagMaxTranslationResidualMeters
                : kSingleTagMaxTranslationResidualMeters)
            && headingResidual <= (multiTag
                ? kMultiTagMaxHeadingResidualRadians
                : kSingleTagMaxHeadingResidualRadians);
    }

    private final Field2d m_field = new Field2d();

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public void resetPose(Pose2d pose) {
        super.resetPose(pose);
    }

    public double closestBumpAngle() {
        double shiftedAngle = this.getState().Pose.getRotation().getRadians() - Math.PI / 4;
        double snappedShifted = Math.round(shiftedAngle / (Math.PI / 2.0)) * (Math.PI / 2.0);
        return snappedShifted + Math.PI / 4;
    }

    private final SwerveRequest.FieldCentric m_fieldCentricDriveRequest = new SwerveRequest.FieldCentric();
    private final SwerveRequest.RobotCentric m_robotCentricDriveRequest = new SwerveRequest.RobotCentric();

    public void drive(double xSpeed, double ySpeed, double rot, boolean fieldRelative) {
        if (!DebugConstants.ALLOW_SWERVE_OUTPUT || !areAllModulesConnected()) {
            this.setControl(m_safeIdleRequest);
            return;
        }

        // TunerConstants.kSpeedAt12VoltsMps is generated by Tuner X.
        // It represents the theoretical max speed of the modules.
        double maxSpeed = TunerConstants.kSpeedAt12Volts.baseUnitMagnitude();
        double limitedX = MathUtil.clamp(
            xSpeed,
            -DebugConstants.MAX_SWERVE_TRANSLATION_FRACTION,
            DebugConstants.MAX_SWERVE_TRANSLATION_FRACTION
        );
        double limitedY = MathUtil.clamp(
            ySpeed,
            -DebugConstants.MAX_SWERVE_TRANSLATION_FRACTION,
            DebugConstants.MAX_SWERVE_TRANSLATION_FRACTION
        );
        double limitedRot = MathUtil.clamp(
            rot,
            -DebugConstants.MAX_SWERVE_ROTATION_RADIANS_PER_SECOND,
            DebugConstants.MAX_SWERVE_ROTATION_RADIANS_PER_SECOND
        );

        if (fieldRelative && isGyroConnected()) {
            m_fieldCentricDriveRequest.VelocityX = limitedX * maxSpeed;
            m_fieldCentricDriveRequest.VelocityY = limitedY * maxSpeed;
            m_fieldCentricDriveRequest.RotationalRate = limitedRot;
            this.setControl(m_fieldCentricDriveRequest);
        } else {
            m_robotCentricDriveRequest.VelocityX = limitedX * maxSpeed;
            m_robotCentricDriveRequest.VelocityY = limitedY * maxSpeed;
            m_robotCentricDriveRequest.RotationalRate = limitedRot;
            this.setControl(m_robotCentricDriveRequest);
        }
    }

    private final SwerveRequest.ApplyRobotSpeeds autoRequest = new SwerveRequest.ApplyRobotSpeeds();

    /** Returns a read-only connectivity snapshot for every CTRE device used by the swerve. */
    public String getDeviceHealthSummary() {
        StringBuilder summary = new StringBuilder();
        summary.append("pigeon").append(getPigeon2().getDeviceID())
            .append('=').append(getPigeon2().isConnected());
        for (int i = 0; i < getModules().length; i++) {
            var module = getModule(i);
            summary.append(" m").append(i)
                .append("[d").append(module.getDriveMotor().getDeviceID())
                .append('=').append(module.getDriveMotor().isConnected())
                .append(",s").append(module.getSteerMotor().getDeviceID())
                .append('=').append(module.getSteerMotor().isConnected())
                .append(",e").append(module.getEncoder().getDeviceID())
                .append('=').append(module.getEncoder().isConnected())
                .append(']');
        }
        return summary.toString();
    }

    public boolean isGyroConnected() {
        return getPigeon2().isConnected();
    }

    /** True only when every CTRE controller and sensor required for swerve motion is online. */
    public boolean areAllDevicesConnected() {
        return isGyroConnected() && areAllModulesConnected();
    }

    /** Module-only health gate; teleop can still fall back to robot-centric if the gyro is absent. */
    public boolean areAllModulesConnected() {
        if (getModules().length == 0) {
            return false;
        }
        for (var module : getModules()) {
            if (!module.getDriveMotor().isConnected()
                    || !module.getSteerMotor().isConnected()
                    || !module.getEncoder().isConnected()) {
                return false;
            }
        }
        return true;
    }

    /** Motion-observed check only; it intentionally does not certify direction or calibration. */
    public boolean hasMinimumModuleSpeed(double minimumMetersPerSecond) {
        if (!Double.isFinite(minimumMetersPerSecond) || minimumMetersPerSecond < 0.0) {
            return false;
        }
        var states = getState().ModuleStates;
        if (states.length == 0) {
            return false;
        }
        for (var state : states) {
            if (!Double.isFinite(state.speedMetersPerSecond)
                    || Math.abs(state.speedMetersPerSecond) < minimumMetersPerSecond) {
                return false;
            }
        }
        return true;
    }

    /**
     * Captures low-output swerve motion evidence, including each drive vector and steer current.
     * This proves neither physical dimensions nor absolute calibration.
     */
    public SwerveDiagnosticEvidence getSwerveDiagnosticEvidence(
            ChassisSpeeds expectedSpeeds,
            double minimumModuleSpeedMetersPerSecond,
            double maximumVectorErrorDegrees,
            double maximumDriveCurrentAmps,
            double maximumSteerCurrentAmps) {
        boolean validRequest = expectedSpeeds != null
            && Double.isFinite(expectedSpeeds.vxMetersPerSecond)
            && Double.isFinite(expectedSpeeds.vyMetersPerSecond)
            && Double.isFinite(expectedSpeeds.omegaRadiansPerSecond)
            && Double.isFinite(minimumModuleSpeedMetersPerSecond)
            && minimumModuleSpeedMetersPerSecond >= 0.0
            && Double.isFinite(maximumVectorErrorDegrees)
            && maximumVectorErrorDegrees >= 0.0
            && Double.isFinite(maximumDriveCurrentAmps)
            && maximumDriveCurrentAmps > 0.0
            && Double.isFinite(maximumSteerCurrentAmps)
            && maximumSteerCurrentAmps > 0.0;
        if (!validRequest) {
            return new SwerveDiagnosticEvidence(
                false, false, false, false, true,
                Double.NaN, Double.NaN, Double.NaN);
        }

        var actualStates = getState().ModuleStates;
        var expectedStates = getKinematics().toSwerveModuleStates(expectedSpeeds);
        boolean connected = areAllDevicesConnected();
        boolean finite = actualStates.length == expectedStates.length && actualStates.length > 0;
        boolean motionObserved = finite;
        boolean steeringAligned = finite;
        boolean overCurrent = false;
        double minimumObservedSpeed = Double.POSITIVE_INFINITY;
        double maximumVectorError = 0.0;
        double maximumObservedDriveCurrent = 0.0;
        double maximumObservedSteerCurrent = 0.0;

        for (int i = 0; i < actualStates.length && i < expectedStates.length; i++) {
            double actualSpeed = actualStates[i].speedMetersPerSecond;
            double expectedSpeed = expectedStates[i].speedMetersPerSecond;
            double driveCurrent = Math.abs(
                getModule(i).getDriveMotor().getStatorCurrent().getValueAsDouble());
            double steerCurrent = Math.abs(
                getModule(i).getSteerMotor().getStatorCurrent().getValueAsDouble());
            if (!Double.isFinite(actualSpeed)
                    || !Double.isFinite(actualStates[i].angle.getRadians())
                    || !Double.isFinite(expectedSpeed)
                    || !Double.isFinite(expectedStates[i].angle.getRadians())
                    || !Double.isFinite(driveCurrent)
                    || !Double.isFinite(steerCurrent)) {
                finite = false;
                motionObserved = false;
                steeringAligned = false;
                continue;
            }

            double absoluteSpeed = Math.abs(actualSpeed);
            minimumObservedSpeed = Math.min(minimumObservedSpeed, absoluteSpeed);
            motionObserved &= absoluteSpeed >= minimumModuleSpeedMetersPerSecond;

            double actualVx = actualSpeed * actualStates[i].angle.getCos();
            double actualVy = actualSpeed * actualStates[i].angle.getSin();
            double expectedVx = expectedSpeed * expectedStates[i].angle.getCos();
            double expectedVy = expectedSpeed * expectedStates[i].angle.getSin();
            double denominator = Math.abs(actualSpeed * expectedSpeed);
            double vectorErrorDegrees = denominator <= 1e-9
                ? 180.0
                : Math.toDegrees(Math.acos(MathUtil.clamp(
                    (actualVx * expectedVx + actualVy * expectedVy) / denominator,
                    -1.0,
                    1.0)));
            maximumVectorError = Math.max(maximumVectorError, vectorErrorDegrees);
            steeringAligned &= vectorErrorDegrees <= maximumVectorErrorDegrees;

            maximumObservedDriveCurrent = Math.max(maximumObservedDriveCurrent, driveCurrent);
            maximumObservedSteerCurrent = Math.max(maximumObservedSteerCurrent, steerCurrent);
            overCurrent |= driveCurrent >= maximumDriveCurrentAmps
                || steerCurrent >= maximumSteerCurrentAmps;
        }

        if (!Double.isFinite(minimumObservedSpeed)) {
            minimumObservedSpeed = Double.NaN;
        }
        return new SwerveDiagnosticEvidence(
            connected && finite,
            motionObserved,
            steeringAligned,
            finite,
            overCurrent,
            minimumObservedSpeed,
            maximumVectorError,
            Math.max(maximumObservedDriveCurrent, maximumObservedSteerCurrent));
    }

    public record SwerveDiagnosticEvidence(
        boolean ready,
        boolean motionObserved,
        boolean steeringAligned,
        boolean telemetryFinite,
        boolean overCurrent,
        double minimumModuleSpeedMetersPerSecond,
        double maximumVectorErrorDegrees,
        double maximumMotorCurrentAmps) {}

    public String getMotionDiagnosticSummary() {
        StringBuilder summary = new StringBuilder();
        var state = getState();
        summary.append(String.format(
            "vx=%.3f vy=%.3f omega=%.3f",
            state.Speeds.vxMetersPerSecond,
            state.Speeds.vyMetersPerSecond,
            state.Speeds.omegaRadiansPerSecond));
        for (int i = 0; i < getModules().length; i++) {
            var module = getModule(i);
            summary.append(String.format(
                " m%d[speed=%.3f angle=%.1f driveI=%.2fA steerI=%.2fA]",
                i,
                state.ModuleStates[i].speedMetersPerSecond,
                state.ModuleStates[i].angle.getDegrees(),
                module.getDriveMotor().getStatorCurrent().getValueAsDouble(),
                module.getSteerMotor().getStatorCurrent().getValueAsDouble()));
        }
        return summary.toString();
    }

    private void configurePathPlanner() {
        m_pathPlannerConfigured = false;
        RobotConfig config;
        try {
            config = RobotConfig.fromGUISettings();
        } catch (Exception e) {
            DriverStation.reportError(
                "PathPlanner robot configuration unavailable: " + e.getMessage(),
                e.getStackTrace());
            return;
        }

        try {
            AutoBuilder.configure(
                () -> this.getState().Pose, // Supplier of current robot pose
                this::resetPose, // Method to reset odometry
                () -> this.getState().Speeds, // Supplier of current robot speeds
                (speeds, feedforwards) -> {
                    if (AutoConstants.CALIBRATED_AUTONOMOUS_ENABLED
                            && DriverStation.isAutonomousEnabled()
                            && DebugConstants.ALLOW_SWERVE_OUTPUT
                            && areAllDevicesConnected()) {
                        double maxTranslation = TunerConstants.kSpeedAt12Volts.baseUnitMagnitude()
                            * DebugConstants.MAX_SWERVE_TRANSLATION_FRACTION;
                        ChassisSpeeds limitedSpeeds = new ChassisSpeeds(
                            MathUtil.clamp(speeds.vxMetersPerSecond, -maxTranslation, maxTranslation),
                            MathUtil.clamp(speeds.vyMetersPerSecond, -maxTranslation, maxTranslation),
                            MathUtil.clamp(
                                speeds.omegaRadiansPerSecond,
                                -DebugConstants.MAX_SWERVE_ROTATION_RADIANS_PER_SECOND,
                                DebugConstants.MAX_SWERVE_ROTATION_RADIANS_PER_SECOND
                            )
                        );
                        this.setControl(autoRequest.withSpeeds(limitedSpeeds));
                    } else {
                        this.setControl(m_safeIdleRequest);
                    }
                }, // Consumer of ChassisSpeeds (Ignore feedforwards for now
                                                         // unless using Torque control)
                new PPHolonomicDriveController(
                        new PIDConstants(5.0, 0.0, 0.0), // Translation PID (kP, kI, kD)
                        new PIDConstants(5.0, 0.0, 0.0) // Rotation PID (kP, kI, kD)
                ),
                config, // The RobotConfig loaded from the GUI settings
                () -> {
                    // Boolean supplier that controls when the path will be mirrored for the red
                    // alliance
                    var alliance = DriverStation.getAlliance();
                    if (alliance.isPresent()) {
                        return alliance.get() == DriverStation.Alliance.Red;
                    }
                    return false;
                },
                this // Reference to this subsystem to set requirements
            );
            m_pathPlannerConfigured = true;
        } catch (RuntimeException e) {
            DriverStation.reportError(
                "PathPlanner AutoBuilder configuration failed: " + e.getMessage(),
                e.getStackTrace());
        }
    }
}
